services:
    sonata.admin.ctl_pacs_establecimiento:
        class: Minsal\SimagdBundle\Admin\CtlPacsEstablecimientoAdmin
        arguments: [~, Minsal\SimagdBundle\Entity\CtlPacsEstablecimiento, MinsalSimagdBundle:CtlPacsEstablecimientoAdmin]
        tags:
            - {name: sonata.admin,event: prePersist ,manager_type: orm, group: admin, label: PACS}

    sonata.admin.ctl_estado_procedimiento_realizado:
        class: Minsal\SimagdBundle\Admin\CtlEstadoProcedimientoRealizadoAdmin
        arguments: [~, Minsal\SimagdBundle\Entity\CtlEstadoProcedimientoRealizado, MinsalSimagdBundle:CtlEstadoProcedimientoRealizadoAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Estado Procedimiento Relalizado}

    sonata.admin.ctl_modalidad_imagenologia:
        class: Minsal\SimagdBundle\Admin\CtlModalidadImagenologiaAdmin
        arguments: [~, Minsal\SimagdBundle\Entity\CtlModalidadImagenologia, MinsalSimagdBundle:CtlModalidadImagenologiaAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: CtlModalidadImagenologia}

    sonata.admin.ctl_examen_imagenologia:
        class: Minsal\SimagdBundle\Admin\CtlExamenImagenologiaAdmin
        arguments: [~, Minsal\SimagdBundle\Entity\CtlExamenImagenologia, MinsalSimagdBundle:CtlExamenImagenologiaAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Ctl Examenes}

    sonata.admin.img_preinscripcion:
        class: Minsal\SimagdBundle\Admin\ImgPreinscripcionAdmin
        arguments: [~, Minsal\SimagdBundle\Entity\ImgPreinscripcion, MinsalSimagdBundle:ImgPreinscripcionAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: ImgPreinscripcion}
