<?php

namespace Minsal\SimagdBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CltEstablecimientoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CltEstablecimientoRepository extends EntityRepository
{
    public function getByEstablecimiento($id) {
     
        return $establecimiento = $this->getEntityManager()
                ->createQueryBuilder()
                ->select('a')
                ->from('MinsalSimagdBundle:CtlEstablecimiento', 'a')
                ->where('a.idTipoEstablecimiento = 1')
                ->getQuery()
                ->getResult();
    }
    
    
}
