<?php

namespace Minsal\SimagdBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CltModalidadImagenologiaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CltModalidadImagenologiaRepository extends EntityRepository
{
    public function obtenerRealizables($idEstablecimiento)
    {
        $query = $this->getEntityManager()
                        ->createQueryBuilder()
                            ->select('m')
                            ->from('MinsalSimagdBundle:CtlModalidadImagenologia', 'm')
                            ->innerJoin('MinsalSimagdBundle:CtlModalidadImagenologiaEstablecimiento', 'mr', 
                                    \Doctrine\ORM\Query\Expr\Join::WITH, 
                                    'm.id = mr.idModalidadImagenologia')
                            ->where('mr.idEstablecimiento = :id_est');
        $query->setParameter('id_est', $idEstablecimiento);        
        
        return $query->getQuery()->getResult();
    }
    
    
}
