<?php

namespace Minsal\SimagdBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CtlPacsEstablecimientoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CtlPacsEstablecimientoRepository extends EntityRepository
{
}
